    const words = [
      { word: "apple", emoji: "🍎" }, { word: "banana", emoji: "🍌" }, { word: "cat", emoji: "🐱" },
      { word: "dog", emoji: "🐶" }, { word: "car", emoji: "🚗" }, { word: "sun", emoji: "☀️" },
      { word: "moon", emoji: "🌙" }, { word: "star", emoji: "⭐" }, { word: "fish", emoji: "🐟" },
      { word: "book", emoji: "📚" }, { word: "milk", emoji: "🥛" }, { word: "fire", emoji: "🔥" },
      { word: "cake", emoji: "🎂" }, { word: "gift", emoji: "🎁" }, { word: "rain", emoji: "🌧️" },
      { word: "snow", emoji: "❄️" }, { word: "tree", emoji: "🌳" }, { word: "frog", emoji: "🐸" },
      { word: "bird", emoji: "🐦" }, { word: "duck", emoji: "🦆" }, { word: "lion", emoji: "🦁" },
      { word: "bear", emoji: "🐻" }, { word: "cow", emoji: "🐄" }, { word: "goat", emoji: "🐐" },
      { word: "bike", emoji: "🚲" }, { word: "bus", emoji: "🚌" }, { word: "ship", emoji: "🚢" },
      { word: "train", emoji: "🚆" }, { word: "plane", emoji: "✈️" }, { word: "watch", emoji: "⌚" },
      { word: "phone", emoji: "📱" }, { word: "mouse", emoji: "🖱️" }, { word: "clock", emoji: "⏰" },
      { word: "heart", emoji: "❤️" }, { word: "candy", emoji: "🍬" }, { word: "bread", emoji: "🍞" },
      { word: "cheese", emoji: "🧀" }, { word: "egg", emoji: "🥚" }, { word: "pizza", emoji: "🍕" },
      { word: "burger", emoji: "🍔" }, { word: "sushi", emoji: "🍣" }, { word: "cookie", emoji: "🍪" },
      { word: "donut", emoji: "🍩" }, { word: "camera", emoji: "📷" }, { word: "tv", emoji: "📺" },
      { word: "robot", emoji: "🤖" }, { word: "alien", emoji: "👽" }, { word: "crown", emoji: "👑" },
      { word: "ghost", emoji: "👻" }, { word: "smile", emoji: "😊" }, { word: "laugh", emoji: "😂" },
      { word: "angry", emoji: "😠" }, { word: "sad", emoji: "😢" }, { word: "sleep", emoji: "😴" },
      { word: "chair", emoji: "🪑" }, { word: "bed", emoji: "🛏️" }, { word: "lamp", emoji: "💡" },
      { word: "key", emoji: "🔑" }, { word: "lock", emoji: "🔒" }, { word: "pen", emoji: "🖊️" },
      { word: "ruler", emoji: "📏" }, { word: "bag", emoji: "👜" }, { word: "shirt", emoji: "👕" },
      { word: "pants", emoji: "👖" }, { word: "shoe", emoji: "👟" }, { word: "hat", emoji: "🎩" },
      { word: "glove", emoji: "🧤" }, { word: "ring", emoji: "💍" }, { word: "soap", emoji: "🧼" },
      { word: "tooth", emoji: "🦷" }, { word: "nail", emoji: "💅" }, { word: "hand", emoji: "✋" },
      { word: "foot", emoji: "🦶" }, { word: "eye", emoji: "👁️" }, { word: "ear", emoji: "👂" },
      { word: "nose", emoji: "👃" }, { word: "hair", emoji: "💇" }, { word: "head", emoji: "🧑" },
      { word: "baby", emoji: "👶" }, { word: "mom", emoji: "👩" }, { word: "dad", emoji: "👨" },
      { word: "family", emoji: "👨‍👩‍👧‍👦" }, { word: "teacher", emoji: "🧑‍🏫" }, { word: "doctor", emoji: "🧑‍⚕️" },
      { word: "nurse", emoji: "👩‍⚕️" }, { word: "pilot", emoji: "👨‍✈️" }, { word: "chef", emoji: "👨‍🍳" },
      { word: "farmer", emoji: "👩‍🌾" }, { word: "police", emoji: "👮" }, { word: "fireman", emoji: "👨‍🚒" },
      { word: "clown", emoji: "🤡" }, { word: "dancer", emoji: "💃" }, { word: "singer", emoji: "🎤" },
      { word: "artist", emoji: "🎨" }, { word: "writer", emoji: "✍️" }, { word: "king", emoji: "🤴" },
      { word: "queen", emoji: "👸" }, { word: "prince", emoji: "👦" }, { word: "princess", emoji: "👧" }
    ];
